### ISSUE TITLE
Stuck in loading files

### ISSUE THREAD

**Issue by genx0521** [arduino/lab-micropython-editor#135] opened 2024-09-15 00:01 UTC
![Capture d’écran 2024-09-14 195834](https://github.com/user-attachments/assets/6fa29d81-28e8-4b78-a9ab-ab15ffcbb9e2)

Hello, 

I have been stuck loading files while opening the Arduino lab for micropython. 

It was working fine and could work with it without a problem. I'm not sure what happened between it working and not working. I have deleted the folder and unzipped a fresh version downloaded and still the same issue. I have tried previous versions as well and still have the same issue. 

Any insight would be great.
;-)

**Comment by genx0521** [comment] 2024-09-15 00:27
Solved the problem - I opened the application as admin and it worked. Even though I am already the admin of my machine.

**Comment by devcylenz** [comment] 2024-10-29 10:24
Had the same problem, the issue is that the tool saves the folder for local files, and if that folder is moved, renamed or deleted, the program is stuck on startup.

**Comment by devcylenz** [comment] 2024-11-01 10:50
The workaround for now is (at least for me it was) to open the devtools inside the arduino lab and check the console. There you can find a warning that some folder can't be found. Create that folder (or folders) so it exists again. Restart the app and you should be good to go.

**Comment by genx0521** [comment] 2024-11-01 11:59
Another solution that worked for me was;  go into %appdata% and find the arduino micropython folder and delete it and restart the application.

**Comment by ubidefeo** [comment] 2024-11-03 10:40
hey folks

@genx0521 's is for now the best solution
>Another solution that worked for me was; go into %appdata% and find the arduino micropython folder and delete it and restart the application.

on Windows the app stores some extra data which it expects at start, but we need to look at why it does so.
Thank you for your patience, we'll look into it

**Comment by gkneen** [comment] 2024-11-05 22:41
To fix this on Linux Mint 22
1. Open the Home folder, right click and choose "show hidden files"
2.  Open the .config folder
3.  Right click on the folder "Arduino Lab for Micropython" and choose "rename"
4. I renamed mine to "Arduino Lab for Micropython.old"
5. Restart the app. It should now ask for  location to save micropython files
6. Delete the .old folder if everything works

**Comment by ubidefeo** [comment] 2024-11-06 19:21
thanks everyone

a fix has been merged, we'll make a new release in a few days 🙏🏼

**Comment by ubidefeo** [comment] 2024-12-17 15:43
Fixed in 0.11.0
https://github.com/arduino/lab-micropython-editor/releases/tag/0.11.0

**Closed by ubidefeo** 2024-12-17 15:43 UTC
