### ISSUE TITLE
REPL is fine but IDE is not working for me.

### ISSUE THREAD

**Issue by Jeff-Squared** [arduino/lab-micropython-editor#20] opened 2022-11-15 15:50 UTC
I have a ESP2 DOIT Devkit v1. connected to a win 64 PC.

Arduino Lab recognizes that I have a device and allows me to connect to the COM port. 

The Folder menu allows me to view the contents of any folder and hi lighting a file enables the upload button but any attempt to upload disconnects the device.

If I hi light boot.py (a file containing a simple blink code) and click the Run menu the terminal goes to Raw REPL and sits there.

If I create a New project it will allow me to code with a title of "undefined", trying to Save or Run disconnects the device.

The panel labelled Board: COM never gets populated with the files on the device.

In the terminal I can use REPL/Raw REPL to reset the device, view the python files on the device copy and paste a program to the device so it seems REPL/Raw REPL works as it should in the terminal.

**Comment by Jeff-Squared** [comment] 2022-11-16 16:49
I must add that it appears to be working better on my Mac. If you need any feedback let me know I would be glad to help.

**Comment by ubidefeo** [comment] 2022-11-17 13:03
@Jeff-Squared 
What Win version are you running?
One of my students did have an issue on her Windows laptop but we were not able to reproduce it elsewhere.
I can start an investigation, might ping you to run some tests if we need help investigating.
Hope we can track it down :)

Thank you for the detailed description on what works and what doesn't, very much appreciated 🙏🏼

**Comment by ubidefeo** [comment] 2022-11-17 13:06
One more, @Jeff-Squared 🙂 
Which version of MicroPython are you running?
Have you tried updating to the latest?

**Comment by Jeff-Squared** [comment] 2022-11-17 16:52
Something I tried this morning that was interesting, there is a sequence of events where I can display the on board files in the IDE.

1. The mcu is connected to the PC
2. Open the Arduino Lab IDE
3. Select the "Files" menu
4. Select the "Folder" menu and choose your preferred repository.
5. Select the "Connect" button and open the connection to the mcu, this opens the terminal when connected.
6. Hit enter until you get the prompt, the prompt is **slow** to appear sometimes.
7. Enter REPL (Ctl B)
8. Enter Raw REPL (Ctl A), the onboard files are visible in the terminal.
9. Go back to the IDE and the onboard files should be visible in the Board: COM panel.
10. I tried this several times with the same result

**Comment by ubidefeo** [comment] 2022-11-18 06:36
hi @Jeff-Squared 
I just got ahold of that board from the bottom of a drawer.
Used the same firmware revision you used.
Flashing it with `esptool.py` took a bit of fiddling, but placing the board in bootloader mode did the trick.

I followed the instructions on MicroPython.org and first erased the flash entirely.
The module is an old ESP32 rev. 1.0

Once it was flashed I had to install the CP2104 universal driver on Windows (which is not your case, since you seem to be able to get to the COM port) and then it just connected and ran.
I'll test on another machine, but only have Windows 10 as a VM on a Mac Pro.
I don't know if testing there is gonna help me get to the bottom of this 😞 

Your breakdown, at point 6, seems odd.
There should be no need to hit ENTER multiple times 🤔 
Any chance you have access to another Win 10 machine to test on?

**Comment by ubidefeo** [comment] 2022-11-18 19:02
@Jeff-Squared 
I have tested on another windows machine (not VM) running Windows 10.
The only thing I had to do was installing the driver for SiLab CP2104 and it worked.
Are you able to identify if you have another USB chip on the board?
I have noticed (on Mac) that WCH serial adapter chips have some strange behaviour (CH340, CH9102), as in they expose two ports, one of which is legacy (is recognised and has limited capabilities) and the other one is supported by recent drivers and allow better integration into the OS.

About a year ago, CP2104 chips by SiLab started coming short on the market, so some manufacturers replaced them with an "equivalent" by WCH which has the peculiarities I have highlighted above.

Try to zoom into the board and take a picture, I'd like to see if the chip is something that might require some "help" to run :)

**Comment by Jeff-Squared** [comment] 2022-11-18 20:20
@ubidefeo  , I will follow up on your request a little later in the mean time I wrote the following in notepad for you to read before I saw this post, I do remeber installing the Silab driver some time ago btw.

Hi, this morning I cleared the flash and reinstalled MicroPython using esptool, the only difference is that my esptool is an exe and not a py extension. The install went well this time and I did not have to press the boot button at all during the installation. There is no difference in it's behaviour it is working well with Thonny.

I agreed with you on item 6 so I played around some more this time with the focus being on the terminal and REPL. I created a video at this link https://youtu.be/djSMJ2_YN8k that I will leave a couple of days to give you the chance to check it out then I will take it down. The video shows Arduino Lab terminal opening in RAW REPL, the terminal is unresponsive until I change to regular REPL, I then change back to RAW REPL and again the terminal is unresponsive. I created a Python app to access the mcu over REPL and ran a quick test to make sure I could access RAW REPL in my app which I did.

I intend to check all this out on another Win machine and also on my Mac, if anything changes I will let you know or if you need more from me I am willing to help.

**Comment by Jeff-Squared** [comment] 2022-11-18 21:47
![ESP32](https://user-images.githubusercontent.com/109444537/202808546-89530393-42ae-459c-9ec0-25fae1e5fdd9.jpg)

**Comment by Jeff-Squared** [comment] 2022-11-19 03:10
@ubidefeo I tested on another Windows machine and everything worked fine, I looked at what you said about Silab and updated my usb vcp driver and yes!! it works. Thank you for your patience and I hope I did not waste too much of your time my problem is now resolved.

**Comment by ubidefeo** [comment] 2022-11-19 11:25
> updated my usb vcp driver and yes!! it works on my machine also now

best start of the weekend ever!

> Thank you for your patience and I hope I did not waste too much of your time my problem is now resolved.
Helping you will help others too.
I want this project to be successful :)

Thank you for helping resolve this.
I'll close the issue 🙏🏼

**Closed by ubidefeo** 2022-11-19 11:25 UTC
Labels: bug
