### ISSUE TITLE
Characters \r\n when loading a file are converted to line breaks in the file itself.

### ISSUE THREAD

**Issue by EugeneRymarev** [arduino/lab-micropython-editor#25] opened 2022-11-23 09:24 UTC
Problem 
![image](https://user-images.githubusercontent.com/6260309/203510976-325302fc-056a-4234-a8fb-f2019fac8939.png)
Original
![image](https://user-images.githubusercontent.com/6260309/203511094-c3bec1b4-5ee9-4b18-9b46-7b2d883506c7.png)
[File](https://github.com/robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD/blob/master/uftpd.py)

**Comment by ubidefeo** [comment] 2022-11-23 11:46
@EugeneRymarev 
Please be more specific with describing your issue.

adding text and code blocks can better help us understand and compare.
Screenshots are not the right way to submit an issue

thank you

**Comment by EugeneRymarev** [comment] 2022-11-23 13:21
@ubidefeo 
[test.zip](https://github.com/arduino/lab-micropython-editor/files/10075812/test.zip)
Try to upload this file.
source
![image](https://user-images.githubusercontent.com/6260309/203556882-31db43bb-f1c6-411b-8ffe-0d070e9fe21f.png)

```
print('200 OK \r\n')

```

result after upload to device
![image](https://user-images.githubusercontent.com/6260309/203557046-372cbbf2-be80-46d4-8357-c1f20ad4cabe.png)

```
print('200 
```

**Comment by jcristine** [comment] 2022-11-26 16:41
I am having the same issue.  The target file on the microcontroller, in my case a Pi Pico W, is truncated at the "\r\n" exactly as shown in the comment above this one.

**Comment by EugeneRymarev** [comment] 2022-11-26 17:03
@jcristine 
You can upload your files via ampy.

**Comment by jcristine** [comment] 2022-11-27 21:54
> "You can upload your files via ampy"

Yes - that is what I've been doing for years but was happy to see that the new Arduino IDE has it all in one UI (unless we use \r\n in code)

**Comment by EugeneRymarev** [comment] 2022-11-28 06:22
@jcristine, I meant that I would have to do this until this bug is fixed. By the way, the plugin for PyCharm has the [same bug](https://github.com/JetBrains/intellij-micropython/issues/212).

**Comment by EugeneRymarev** [comment] 2022-11-29 09:08
@ubidefeo, do you understand the problem?

**Comment by murilopolese** [comment] 2022-12-01 14:41
Thank you @EugeneRymarev for the report!
I think this is expected due to the way we are saving files on the board. 
The IDE (currently) send files to be board as text strings and I think this is the reason for the behaviour you reported.
I think we should look into this, @ubidefeo :+1:

**Comment by murilopolese** [comment] 2022-12-05 08:40
I did a quick investigation and I can reproduce the bug.
My new guess is that the method `read_until` from `micropython.js` may be related to the issue: 
https://github.com/arduino/lab-micropython-editor/blob/main/micropython.js#L72

**Comment by chrisbuerginrogers** [comment] 2023-01-21 18:04
I solved it by converting the desired string to binary and then writing it out as hex values:

gc.collect()
with open("Fred.py","wb") as bfile:
    f = bfile.write(bytes([0x73,0x22,0x10])).  #I do this in 256 byte chunks (so not these three random numbers)
    f = bfile.write(bytes([0x73,0x22,0x10]))
    f = bfile.write(bytes([0x73,0x22,0x10]))
    f = bfile.write(bytes([0x73,0x22,0x10]))

That seems to work fairly flawlessly

**Comment by ubidefeo** [comment] 2024-04-19 07:09
Fixed in 0.9.x

**Closed by ubidefeo** 2024-04-19 07:09 UTC
