### ISSUE TITLE
Version number not updated in  "about" info banner

### ISSUE THREAD

**Issue by jaenrig-ifx** [arduino/lab-micropython-editor#40] opened 2023-04-21 10:35 UTC
After downloading the 0.7.0 release for windows, it seems the about version information is not properly updated:
![image](https://user-images.githubusercontent.com/47138227/233615118-9e36c5b1-e4d0-45e1-9ff3-2f26c58063e7.png)

**Comment by per1234** [comment] 2023-04-21 14:04
Thanks for your report @jaenrig-ifx! An equivalent problem was also reported for the previous release: https://github.com/arduino/lab-micropython-editor/issues/31
That issue was closed by the reporter, but the cause of the mismatched version data was never identified. So I'm not implying this issue is a duplicate; but only linking to relevant information.

**Comment by per1234** [comment] 2023-04-21 14:07
In this case it appears the problem is that the metadata was not bumped prior to the release:

https://github.com/arduino/lab-micropython-editor/blob/0.7.0/package.json#L4

https://github.com/arduino/lab-micropython-editor/blob/b15464b75990fa5e85e241eace00a1e4bc5e09cd/package.json#L4

It might be useful to document a release procedure. We found this very useful for the release managers in the Arduino IDE 2.x project:

https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#release-procedure

**Comment by ubidefeo** [comment] 2024-04-19 07:28
We are paying more attention to the version number in the `package.json`,
but we'll definitely write a release procedure document.
This issue will be closed

**Closed by ubidefeo** 2024-04-19 07:28 UTC
Labels: bug
