### ISSUE TITLE
NO way to connect with COM ports over 16

### ISSUE THREAD

**Issue by DynoDon** [arduino/lab-micropython-editor#100] opened 2024-04-04 19:29 UTC
My arduino has a port number of 20 and is not listed when I press the connect button.

**Comment by ubidefeo** [comment] 2024-04-09 19:33
Thank you for reporting.

This looks like an interesting bug we have not noticed yet.
I'll run some tests by manually renaming a COM and see what happens.

Be back to you with my findings
u.

**Comment by ubidefeo** [comment] 2024-04-09 20:02
I have not been able to connect to any port above COM9.
Tracking this issue, thank you :)

**Comment by ubidefeo** [comment] 2024-04-19 07:56
@DynoDon 
while I am able to reproduce it in a Virtual Machine, our colleagues can't seem to be able to.
We'll leave this issue open, hoping someone else will find it and offer hints if it happens to them.

Please try 0.9.1 and let me know if it is still a valid issue.
I'd also suggest not to have USB hubs or expanders between your board and your computer.
It is often advised against (even though I do 😬 )

**Comment by ubidefeo** [comment] 2024-12-17 15:50
Should be fixed in 0.11.0
https://github.com/arduino/lab-micropython-editor/releases/tag/0.11.0

**Closed by ubidefeo** 2024-12-17 15:50 UTC
