### ISSUE TITLE
Apostrophes not buffered correctly in combination with special character in REPL

### ISSUE THREAD

**Issue by StevenCellist** [arduino/lab-micropython-editor#27] opened 2022-12-14 08:24 UTC
In most languages, characters like ```'``` and ```"``` are buffered until a second character has been typed.
The REPL however buffers these incorrectly: typing either of these two, followed by another special character, results in that special character rendered twice instead of rendering the apostrophe and special character.

Example: typing ```"]``` results in ```]]```, unless specifically entering ```␣``` after the apostrophe.

**Comment by ubidefeo** [comment] 2023-01-03 14:49
hey @StevenCellist 
I tried to figure out what you mean but to be honest haven't been able to understand

**Comment by StevenCellist** [comment] 2023-01-03 15:15
Hey @ubidefeo, thanks for following this up!
I hope I can be clear enough. 

An example: typing the following in the Terminal
```python
x["test"]
```
... results in ...
```python
x["test]]
```
This only happens on a keyboard-language which buffers the " for use in e.g. ä and ë.

An example is the Dutch (NL) keyboard.

Hope that helps!

**Comment by ubidefeo** [comment] 2023-01-21 17:01
hey @StevenCellist 

I cannot reproduce that one on Mac.
Even using combinations of ALT and '`' to add a modifier of following character it won't happen.
What OS are you on?

**Comment by StevenCellist** [comment] 2023-01-24 19:58
Windows; I have tried it on multiple machines and v0.6 has the same problem on my pc.

**Comment by murilopolese** [comment] 2023-02-13 14:11
I can't reproduce either. I'm on a linux machine with Swedish keyboard.


![Image](https://user-images.githubusercontent.com/954594/218480340-b02e697f-734a-4fcc-8f86-05eae0ab946a.png)


One thing to take in consideration is that the console/repl itself is not part of the editor. 
The source code and character parsing happens inside the board, by the micropython firmware.
All that the editor does is to pipe the keystrokes through serial exactly the way they are being captured by the javascript listeners.

I would recommend trying to type the same thing with another software such as `screen` or another serial monitor to see if the problem is with the javascript. If you are typing a combination of keys to input `"` the problem may be out of our reach :T

**Comment by ubidefeo** [comment] 2023-06-16 07:03
@StevenCellist 
we have completely reworked the escape/encode part of the save/upload workflows.
The bug will be fixed in upcoming `0.8.0`

**Comment by ubidefeo** [comment] 2024-04-19 07:10
Closed for non-reproducibility and staleness

**Closed by ubidefeo** 2024-04-19 07:10 UTC
Labels: bug
